ba-backend/config/routes.rb
Rails.application.routes.draw do

  root "flights#index"
  resources :airplanes
  resources :flights
  resources :reservations
  resources :users
  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"
end

ba-backend/app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
end

ba-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ba-backend/app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airplane
end

ba-backend/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :flight
  belongs_to :user
end

ba-backend/app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
end

ba-backend/app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    @airplane = Airplane.new
  end

  def create
    Airplane.create(airplane_params)
    redirect_to
  end

  def index
    @airplanes = Airplane.all
    # render json: Airplane.all
    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @airplanes }

    end #respond to
  end

  def show
    @airplane = Airplane.find params[:id]
  end

  def update
    @airplane = Airplane.find params[:id]
    @airplane.save

    if @airplane.update(airplane_params)
      redirect_to( airplane_path( @airplane.id ) )
    else
      flash[:errors] = @airplane.errors.full_messages
      render :edit
    end
  end

  def edit
    @airplane = Airplane.find params[:id]
  end

  def destroy
    airplane = Airplane.find params[:id]
    airplane.destroy
    redirect_to airplanes_path
  end

  private
  def airplane_params
    params.require(:airplane).permit(:name, :rows, :columns)
  end
end

ba-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    # check if session[:user_id] is set, and also if it stores a valid ID, and if so, set an instance varibale containing the user object

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # Make sure we actually found a valid user (i.e. the User ID in the session wasn't stale, from a deleted account)
    # and if we didn't get a valid user (in @current_user) then we clear the session key
    session[:user_id] = nil unless @current_user.present?
  end
end

ba-backend/app/controllers/flight_controller.rb
class FlightController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def show
  end

  def edit
  end

  def update
  end
end

ba-backend/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    @flight = Flight.new
  end

  def create
    Flight.create(flight_params)
    redirect_to
  end

  def index
    @flights = Flight.all
    # render json: Flight.all
    # need to render out to html and json
    respond_to do |format|

      format.html # show.html.erb
      format.json { render json: @flights }

    end #respond to
  end

  def show
    @flight = Flight.find params[:id]
  end

  def update
    @flight = Flight.find params[:id]
    @flight.save

    if @flight.update(flight_params)
      redirect_to( flight_path( @flight.id ) )
    else
      flash[:errors] = @flight.errors.full_messages
      render :edit
    end
  end

  def edit
    @flight = Flight.find params[:id]
  end

  def destroy
    flight = Flight.find params[:id]
    flight.destroy
    redirect_to flights_path
  end

  private
  def flight_params
    params.require(:flight).permit(:flight_no, :date, :origin, :destination, :airplane_id)
  end
end

ba-backend/app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def show
  end

  def edit
  end

  def update
  end
end

ba-backend/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    @reservation = Reservation.new
  end

  def create
    # @reservation = Reservation.new(reservation_params)
    # @reservation.user = @current_user
    # @flights = Flight.all
    # @reservation.flights << Flight.find(params[:flights])
    # @reservation.save
    # # console
    # # raise "hell"


    reservation = Reservation.create(user_id: params[:user_id], flight_id: params[:flight_id], seat_row: params[:seat_row], seat_column: params[:seat_column])
    render json: {reservation: reservation, created: true}
  end


  def index
    render json: Reservation.all
  end

  def show
    @reservation = Reservation.find params[:id]
  end

  def update
    @reservation = Reservation.find params[:id]
    @reservation.flights.destroy_all
    @flights = Flight.all
    @reservation.flights << Flight.find(params[:flights])
    @reservation.save
    # console
    # raise "hell"

    unless @reservation.user == @current_user
      flash[:errors] = @reservation.errors.full_messages
      render :edit
    end

    if @reservation.flights.length == 7
      # @reservation.save
      if @reservation.update(reservation_params)
        redirect_to( reservation_path( @reservation.id ) )
      end
    else
      flash[:errors] = @reservation.errors.full_messages
      render :edit
    end
  end

  def edit
    @reservation = Reservation.find params[:id]
    @flights = Flight.all
  end

  def destroy
    reservation = Reservation.find params[:id]
    reservation.destroy
    redirect_to reservations_path
  end

  private
  def reservation_params
    params.require(:reservations).permit(:user_id, :flight_id, :seat_row, :seat_column)
  end
end

ba-backend/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by name: params[:name]
    if user.present?

      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:error] = "User Must Be Logged In"
      redirect_to( login_path )
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

ba-backend/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def show
  end

  def edit
  end

  def update
  end
end

ba-backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create user_params # strong params

    if user.persisted?
      # Account created successfully!
      session[:user_id] = user.id # Log in the new user!!
      # redirect_to user_path(user) # go to the show page for this user
      redirect_to flights_path
    else


      flash[:errors] = user.errors.full_messages
      # redirect_to new_user_path
      redirect_to flights_path
    end
  end

  def index
    # @user = User.all
    render json: User.all
  end

  def show
    @user = User.find params[:name]
  end

  def update
    @user = User.find params[:id]
    @user.save

    if @user.update(user_params)
      redirect_to( user_path( @user.id ) )
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def edit
    @user = User.find_by id: session[:user_id]

  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

ba-backend/app/helpers/airplane_helper.rb
module AirplaneHelper
end

ba-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

ba-backend/app/helpers/flight_helper.rb
module FlightHelper
end

ba-backend/app/helpers/reservation_helper.rb
module ReservationHelper
end

ba-backend/app/helpers/session_helper.rb
module SessionHelper
end

ba-backend/app/helpers/user_helper.rb
module UserHelper
end

ba-backend/app/views/airplanes/_form.html.erb
<%= form_for @airplane do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :rows %>
    <%= f.text_field :rows %>
  </fieldset>
  <fieldset>
    <%= f.label :columns %>
    <%= f.text_field :columns %>
  </fieldset>

  <%= f.submit %>

<% end %>

ba-backend/app/views/airplanes/create.html.erb
<h1>Airplane#create</h1>
<p>Find me in app/views/airplane/create.html.erb</p>

ba-backend/app/views/airplanes/destroy.html.erb
<h1>Airplane#destroy</h1>
<p>Find me in app/views/airplane/destroy.html.erb</p>

ba-backend/app/views/airplanes/edit.html.erb
<h1>Airplane Edit</h1>
<h2><%= @airplane.name %></h2>

<%= render partial: 'form' %>

ba-backend/app/views/airplanes/index.html.erb
<h2>Airplanes Listing</h2>

<ul>
<% @airplanes.each do |airplane| %>
  <li>
    <%= link_to airplane.name, airplane_path(airplane.id) %>
  </li>
<% end %>
</ul>

ba-backend/app/views/airplanes/new.html.erb
<h2>Add New Airplane</h2>

<%= render partial: 'form' %>

ba-backend/app/views/airplanes/show.html.erb
<h2><%= @airplane.name %></h2>


<p>Rows: <%= @airplane.rows %></p>
<p>Columns: <%= @airplane.columns %></p>


<br>

<%= link_to 'Edit This Airplane', edit_airplane_path(@airplane) %>
|
<%= link_to 'Delete This Airplane', airplane_path(@airplane), method: 'delete' %>

ba-backend/app/views/airplanes/update.html.erb
<h1>Airplane#update</h1>
<p>Find me in app/views/airplane/update.html.erb</p>

ba-backend/app/views/flights/_form.html.erb
<%= form_for @flight do |f| %>
  <fieldset>
    <%= f.label :flight_no %><!-- gives us a <label> tag -->
    <%= f.text_field :flight_no %> <!-- gives us <input type="text" name="name"> -->
  </fieldset>
  <fieldset>
    <%= f.label :date, 'Flight Date' %>
    <%= f.text_field :date %>
  </fieldset>

  <fieldset>
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </fieldset>
  <fieldset>
    <%= f.label :destination %>
    <%= f.text_field :destination %>
  </fieldset>
  <fieldset>
    <%= f.label :airplane_id, 'Airplane' %>
    <%= f.collection_select :airplane_id, Airplane.all, :id, :name, prompt: 'Please choose an airplane:' %>
  </fieldset>
  <%= f.submit %>

<% end %>

ba-backend/app/views/flights/create.html.erb
<h1>Flight#create</h1>
<p>Find me in app/views/flight/create.html.erb</p>

ba-backend/app/views/flights/destroy.html.erb
<h1>Flight#destroy</h1>
<p>Find me in app/views/flight/destroy.html.erb</p>

ba-backend/app/views/flights/edit.html.erb
<h1>Flight Edit</h1>
<h2><%= @flight.flight_no %></h2>

<%= render partial: 'form' %>

ba-backend/app/views/flights/index.erb
<h2>Flight Listings</h2>

<ul>
<% @flights.each do |flight| %>
  <li>
    <%= link_to flight.flight_no, flight_path(flight.id) %>
    <h4> Flight Date: <%= flight.date %>  >>>  Flight Origin: <%= flight.origin %>  >>>  Flight Destination: <%= flight.destination %></h4>
  </li>
<% end %>
</ul>

ba-backend/app/views/flights/new.html.erb
<h2>Add New Flight</h2>

<%= render partial: 'form' %>

ba-backend/app/views/flights/show.html.erb
<h2><%= @flight.flight_no %></h2>
<hr>

<p>Flight: <%= @flight.date.to_formatted_s(:long_ordinal) %></p>
<p>Origin: <%= @flight.origin %></p>
<p>Destination: <%= @flight.destination %></p>

<br>

<%= link_to 'Back to Flights', flights_path %>
|
<%= link_to 'Edit This Flight', edit_flight_path(@flight) %>
|
<%= link_to 'Delete This Flight', flight_path(@flight), method: 'delete' %>

ba-backend/app/views/flights/update.html.erb
<h1>Flight#update</h1>
<p>Find me in app/views/flight/update.html.erb</p>

ba-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <h1>Burning Airlines</h1>
    <nav>
    <h3><%= link_to 'Create New User', new_user_path %>|<%= link_to 'Create New Flight', new_flight_path %> | <%= link_to 'Back to Flights', flights_path %> | <%= link_to 'Airplane Listing', airplanes_path%> | <%= link_to 'Create New Airplane', new_airplane_path %></h3>
    </nav>
    <hr>
    <%= yield %>
  </body>
</html>

ba-backend/app/views/reservations/create.html.erb
<h1>Reservation#create</h1>
<p>Find me in app/views/reservation/create.html.erb</p>

ba-backend/app/views/reservations/destroy.html.erb
<h1>Reservation#destroy</h1>
<p>Find me in app/views/reservation/destroy.html.erb</p>

ba-backend/app/views/reservations/edit.html.erb
<h1>Reservation#edit</h1>
<p>Find me in app/views/reservation/edit.html.erb</p>

ba-backend/app/views/reservations/new.html.erb
<h1>Reservation#new</h1>
<p>Find me in app/views/reservation/new.html.erb</p>

ba-backend/app/views/reservations/show.html.erb
<h1>Reservation#show</h1>
<p>Find me in app/views/reservation/show.html.erb</p>

ba-backend/app/views/reservations/update.html.erb
<h1>Reservation#update</h1>
<p>Find me in app/views/reservation/update.html.erb</p>

ba-backend/app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

ba-backend/app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

ba-backend/app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

ba-backend/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <fieldset>
    <%= f.label :name %><!-- gives us a <label> tag -->
    <%= f.text_field :name %> <!-- gives us <input type="text" name="name"> -->
  </fieldset>

  <%= f.submit %>

<% end %>

ba-backend/app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

ba-backend/app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

ba-backend/app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

ba-backend/app/views/users/new.html.erb
<h2>Add New User</h2>

<%= render partial: 'form' %>

ba-backend/app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

ba-backend/app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>